function picture = predictionStep(picture,p)
%
% $Id: predictionStep.m,v 1.3 2007/05/07 11:09:47 sho Exp $
%
% Copyright (C) 2005-2015 Shogo MURAMATSU, All rights reserved
%
if (mod(size(picture,1),2)==0)
    picture(2:2:end,:) = picture(2:2:end,:) ...
        + p * ( ...
            picture(1:2:end,:) ...
            + [picture(3:2:end,:); picture(end-1,:)] ...
            );
else
    picture(2:2:end,:) = picture(2:2:end,:) ...
        + p * ( ...
            picture(1:2:end-2,:) ...
            + picture(3:2:end,:) ...
            );
end
