function picture = updateStep(picture,u)
%
% $Id: updateStep.m,v 1.3 2007/05/07 11:09:47 sho Exp $
%
% Copyright (C) 2005-2015 Shogo MURAMATSU, All rights reserved
%

if (mod(size(picture,1),2)==0)
    picture(1:2:end,:) = picture(1:2:end,:) ...
        + u * ( ...
            [picture(2,:); picture(2:2:end-1,:)] ... 
            + picture(2:2:end,:) ...
            );
else
    picture(1:2:end,:) = picture(1:2:end,:) ...
        + u * ( ...
            [picture(2,:); picture(2:2:end-1,:)] ... 
            + [picture(2:2:end,:); picture(end-1,:)] ...
            );
end