function z = mcClellanTrans(w1,w0,parameters)
%
% $Id: downsample2.m,v 1.2 2007/05/07 11:09:47 sho Exp $
%
% Copyright (C) 2006-2015 Shogo MURAMATSU, All rights reserved
%
z = parameters.A +...
    parameters.B * cos(w0) + ...
    parameters.C * cos(w1) + ...
    parameters.D * cos(w0-w1) +...
    parameters.E * cos(w0+w1);
