%[text] # Sample 6-6
%[text] ## 標本化
%[text] 二変量アップサンプリング
%[text] 画像処理特論
%[text] 村松 正吾 
%[text] 動作確認: MATLAB R2023a
%[text] ## Sampling
%[text] Bivariate upsampling
%[text] Advanced Topics in Image Processing
%[text] Shogo MURAMATSU
%[text] Verified: MATLAB R2023a
%%
%[text] ### 準備
%[text] (Preparation)
close all
%%
%[text] ### 可分離間補間行列の設定
%[text] (Setting a separable upsampling factor)
%[text] - $\\mathbf{M}$: 補間行列 (upsampling factor) \
%[text]  可分離の場合 (In the separable case)
%[text]  $\\mathbf{M}=\\left(\\begin{array}{cc} M\_1 & 0 \\\\ 0 & M\_2 \\end{array}\\right)\\in \\mathbb{Z}^{2\\times 2}$
% Vertical upsampling ratio
verticalUFactor = 2;  %[control:slider:42f3]{"position":[19,20]}
% Horizontal upsampling factor
horizontalUFactor = 3;  %[control:slider:7d86]{"position":[21,22]}
%%
%[text] ### 入力配列の設定
%[text] (Setting an input array)
%[text] - $\\{u\[\\mathbf{n}\]\\}\_\\mathbf{n}$: 入力配列 (input array) \
% Standard deviation 
sigma = 2;
% Array size
sizeU = 31;

% Generate an array with bivariate Gaussian function
arrayU = fspecial('gaussian',sizeU,sigma);
%%
%[text] ### 入力配列のスペクトル
%[text] (Spectrum of the input array)
% Spectrum of u[n]
figure(1)
freqz2(arrayU)
xlabel('\omega_2 (\times\pi rad)')
ylabel('\omega_1 (\times\pi rad)')
title('Before upsampling')
axis ij
%%
%[text] ### 出力配列の計算
%[text] (Computation of the output array)
%[text] - $\\{v\[\\mathbf{m}\]\\}\_\\mathbf{m}$: 出力数列 (output sequence) \
%[text]  $v\[\\mathbf{m}\] = \\left\\{\\begin{array}{ll}  u\[\\mathbf{M}^{-1}\\mathbf{m}\] & \\mathbf{m}\\in\\mathcal{L}(\\mathbf{M}) \\\\ 0 &\\mathrm{otherwise} \\\\ \\end{array}\\right.$
%[text]  $\\mathcal{L}(\\mathbf{M})\\colon = \\{\\mathbf{Mk} | \\mathbf{k}\\in\\mathbb{Z}^2\\}$
% Definition of bivariate separable upsampling
upsample2 = @(x,n) ...
    shiftdim(upsample(...
    shiftdim(upsample(x,...
    n(1)),1),...
    n(2)),1);

% Bivariate separable upampling
arrayV = upsample2(arrayU, [verticalUFactor horizontalUFactor]);
%%
%[text] ### 出力配列のスペクトル
%[text] (Spectrum of the output array)
figure(2)
freqz2(arrayV)
xlabel('\omega_2 (\times\pi rad)')
ylabel('\omega_1 (\times\pi rad)')
title('After upsampling')
axis ij
%%
%[text] ### 非可分補間行列の設定
%[text] (Setting a non-separable upsampling factor)
%[text] - $\\mathbf{M}$: 補間行列 (upsampling factor) \
%[text]  一般的な場合 (In the general case)
%[text]  $\\mathbf{M}=\\left(\\begin{array}{cc} \\mathbf{m}\_{1} & \\mathbf{m}\_{2} \\end{array}\\right)\\in \\mathbb{Z}^{2\\times 2}$
% Upsampling factor
upMtx = [ 1 1 ; -1 1 ];
%%
%[text] ### 入力配列の設定
%[text] (Setting an input array)
% Covariance matrix
covMtx  = [2 0 ; 0 1/2];
% Array size
sizeU = 31;

% Generate an array with bivariate Gaussian function
arrayU = mygaussian2(sizeU,covMtx);

% Spectrum of u[n]
figure(3)
freqz2(arrayU)
xlabel('\omega_2 (\times\pi rad)')
ylabel('\omega_1 (\times\pi rad)')
title('Before upsampling')
axis ij
%%
%[text] ### 出力配列の計算
%[text] (Computation of the output array)
% Bivariate non-separable upsampling
arrayV = myupsample2(arrayU,upMtx);

% Spectrum of v[m]
figure(4)
freqz2(arrayV)
xlabel('\omega_2 (\times\pi rad)')
ylabel('\omega_1 (\times\pi rad)')
title('After upsampling')
axis ij
%%
%[text] ### プライベート関数の定義
%[text] (Definitions of private functions)
%[text] 二変量ガウス配列の生成関数　(Generation function of bivariate Gaussian arrays)
function x = mygaussian2(sizeX, covMtx)
% MYGAUSSIAN2
%
% Inputs
%
%   sizeX: size of output array 
%   covMtx: covariance matrix
%
% Output
%
%   x: array generated by Gauss Func. 
%
sizeHalf = floor(sizeX / 2);

if isscalar(covMtx)
    covMtx = covMtx * eye(2);
end

x = zeros(sizeHalf*2);
iRow = 1;
for n1 = -sizeHalf:sizeHalf
    iCol = 1;
    for n0 = -sizeHalf:sizeHalf    
        p = - 0.5 * [ n0 n1 ] * (covMtx\[ n0 n1 ].');
        x(iRow,iCol) = exp(p);
        iCol = iCol + 1;
    end
    iRow = iRow + 1;
end
x = x / sum(sum(x));

end % of mygaussian2
%[text] 二変量非可分アップサンプリング関数 (bivariate non-separable upsampling function)
function [outputArray, X, Y] = myupsample2(inputArray,upMtx)
% MYUPSAMPLE2
%
% Inputs
%
%   inputArray: input array
%   upMtx: upsampling matrix
%
% Outputs
%
%   outputArray: output array 
%   X          : horizontal sampling points
%   Y          : vertical sampling points
%

% Size of input array
nRowsInputArray = size(inputArray,1);
nColsInputArray = size(inputArray,2);
nCompInputArray = size(inputArray,3);

% Calculation of the support region after upsampling
vertexPoints(:,1) = [ 0 0 ].';
vertexPoints(:,2) = upMtx * [ 0 nColsInputArray ].';
vertexPoints(:,3) = upMtx * [ nRowsInputArray 0 ].';
vertexPoints(:,4) = upMtx * [ nRowsInputArray nColsInputArray ].';
minPoint = floor(min(vertexPoints,[],2));
maxPoint = ceil(max(vertexPoints,[],2))-1;

% Upsampling
clear arrayY
iRow = 1;
for m0 = minPoint(1):maxPoint(1)
    iCol = 1;
    for m1 = minPoint(2):maxPoint(2)
        outputArray(iRow, iCol, :) = zeros(1,nCompInputArray,...
                'like',inputArray);        
        originalPoint = upMtx \ [ m0 m1 ].';
        lat = upMtx * fix(originalPoint);
        if m0 == lat(1) && m1 == lat(2)
            n0 = originalPoint(1);
            n1 = originalPoint(2);
            if n0 >= 0 && n0 < nRowsInputArray  && ...
                n1 >= 0 && n1< nColsInputArray
                outputArray(iRow, iCol, :) = inputArray(n0 + 1, n1 + 1, :);    
            end
        end
       iCol = iCol + 1;
    end
    iRow = iRow + 1;
end

Y = minPoint(1):maxPoint(1);
X = minPoint(2):maxPoint(2);

end % of myupsample2
%[text] © Copyright, Shogo MURAMATSU, All rights reserved.

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline","rightPanelPercent":40}
%---
%[control:slider:42f3]
%   data: {"defaultValue":2,"label":"verticalUFactor","max":8,"min":2,"run":"SectionToEnd","runOn":"ValueChanging","step":1}
%---
%[control:slider:7d86]
%   data: {"defaultValue":3,"label":"horizontalUFactor","max":8,"min":2,"run":"SectionToEnd","runOn":"ValueChanging","step":1}
%---
